### DISCUSSION TITLE
how to make myst the defaulf markdown file format

### DISCUSSION THREAD

**Discussion by franzhaas** [jupyterlab/jupyterlab#15575] [Q&A]
Dear all,

I would like to create a myst markdown file instead of an regular mark down file when clicking File -> New Notebook, AND when clicking File -> New Markdown

This type of markdown file.:
```
---
jupytext:
  text_representation:
    extension: .md
    format_name: myst
    format_version: 0.13
    jupytext_version: 1.15.2
kernelspec:
  display_name: sobel_groundhog
  language: python
  name: sobel_groundhog
---
```

Any ideas how to do that? Idealy for all users?

Thanks,
Franz
