### ISSUE TITLE
When too many tabs are open in a supanel they overflow

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#10305]
## Description

When too many tabs are open in a supanel they overflow

## Reproduce

![Screenshot from 2021-05-27 14-49-51](https://user-images.githubusercontent.com/5832902/119838146-14cd4e00-befb-11eb-93f4-ae9e1e333d5a.png)

## Expected behavior

I would expect the tab bar to be horizontally scrollable instead of overflowing.

## Context

- Browser and version: Chrome
- JupyterLab version: 3.0.14

**Comment by krassowski** [comment]
Adding:

```css
.lm-Widget.p-Widget.lm-TabBar.p-TabBar.lm-DockPanel-tabBar.jp-Activity {
    overflow-x: scroll;
}
```

Partially solves the issue, but scrollbars would need to be styled to make it usable:

![Screenshot from 2021-05-27 14-55-41](https://user-images.githubusercontent.com/5832902/119838969-b94f9000-befb-11eb-87e1-c2e4687100db.png)

I think that a very narrow scrollbar of 2/3px would be enough.
