### ISSUE TITLE
Publish test results as a PR comment 

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#10968]
### Problem

For now `galata` is able to generate a repot with the test results, as demoed in https://github.com/jupyter-widgets/ipywidgets/pull/3172#issuecomment-807587761:

![image](https://user-images.githubusercontent.com/40003442/112549807-9d086900-8d7b-11eb-84db-6baff4347d5e.png)

It would be nice if these reports could make it to the PR as a comment when galata is running on CI.

When doing visual regression testing, there could even be the diff between two screenshots.

### Proposed Solution

This might be fixed by documentation. Or by having a galata GitHub Action that could automate some of this.

### Additional context

cc @martinRenou who is also interested in this

<!-- Add any other context or screenshots about the feature request here. You can also include links to examples of other programs that have something similar to your request. For example:

* Another project [...] solved this by [...]

**Comment by martinRenou** [comment]
@fcollonval for awareness

**Comment by krassowski** [comment]
Now with https://github.com/jupyterlab/jupyterlab/pull/18628 in we are publishing self-contained playwright reports viewable in the browser. The remaining issue is that they are not super discoverable, one needs to navigate to job summary (which is not really available on GitHub mobile app) - and know where to find it.

I think exposing this in the comments thread would be valuable. I am just not sure if we want to add another comment (given how GitHub struggles to display longer conversations) or instead just modify the top-level comment by appending the URL at the end. What do folks think?

**Comment by jasongrout** [comment]
> I am just not sure if we want to add another comment (given how GitHub struggles to display longer conversations) or instead just modify the top-level comment by appending the URL at the end. What do folks think?

When we make a PR to the jupyter.github.io repo, the details link for the "deploy/netlify — Deploy Preview ready!" job just brings us straight to the website preview. I'm not sure how that works, but is there a way to make a CI job where clicking on the details brings up this playwright report directly? Then the results are one click away from the CI listing at the bottom of the PR.

I don't think I've usually seen a CI job modify the top comment, and especially now that the top comment is the default squash commit message (so presumably people are editing it quite a bit), I don't know that we want to be automatically modifying it adding/replacing stuff? I think for these reasons I'd prefer a comment, or perhaps editing the first such automatic comment made?

*Edit: oh, I see Jeremy also suggested above the netlify deploy preview as a good example*

**Comment by krassowski** [comment]
> I don't think I've usually seen a CI job modify the top comment

It is pretty common for LLMs to add summaries ([Devin](https://docs.devin.ai/work-with-devin/devin-review#admin-configuration), [CodeRabbit](https://docs.coderabbit.ai/pr-reviews/summaries)), Qodo Merge; preview links are indeed more often added in a comment (Netlify, Vercel, Cloudflare, Render) as are code coverage reports (Codecov, Coveralls). Maybe the difference is that in AI era the assumption is that human would edit the PR description less often?

Together with the concern about race condition when user edits it, I think this makes a good case against adding it to the PR description. My main concern was that the comment will get collapsed by GitHub once conversation grows, but indeed, a `deploy/netlify — Deploy Preview ready` style link from the CI job summary can help with it if pinned as "required".

<img width="874" height="397" alt="Image" src="https://github.com/user-attachments/assets/5d1e94f3-0472-42af-a333-0e3df19615af" />

> I'm not sure how that works, but is there a way to make a CI job where clicking on the details brings up this playwright report directly?

I will look into it; the problem might be that the netlify does that by being an external integration rather than GitHub Action so I am not sure if we can do it.

But maybe instead we could use "View Deployment" button? Or would it be too confusing?

<img width="886" height="203" alt="Image" src="https://github.com/user-attachments/assets/4f6a16df-4c22-446e-aa45-8899b3ae9180" />

This is easily achieved with https://github.com/marketplace/actions/deployment-action or just plain script, possibly:

```yaml
- name: Update Deployment Status
  if: always()
  uses: actions/github-script@v7
  with:
    script: |
      await github.rest.repos.createDeploymentStatus({
        owner: context.repo.owner,
        repo: context.repo.repo,
        deployment_id: ${{ steps.upload_inline_report.step_id }},
        state: 'success',
        environment_url: '${{ steps.merge_reports.report_url }}',
        description: 'Integration tests report ready!',
        log_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
      });
```

Older blog post about this approach: https://sanderknape.com/2020/05/deploy-pull-requests-github-actions-deployments/

I guess the con of "View Deployment" is that it adds more noise in UI (adds entries on PR timeline when deployment starts, ends etc) and we some folks would expect that link to lead to Binder style preview rather than a report instead.

> or perhaps editing the first such automatic comment made?

As in adding to the Binder link? Maybe we could have it there too. I think this is the least friction/least controversial option?
