### ISSUE TITLE
ui-components CSS should probably not change "global" elements CSS?

### ISSUE THREAD

**Issue by martinRenou** [jupyterlab/jupyterlab#13493]
## Description

ui-components's CSS contains the following:

```css
body {
  color: var(--jp-ui-font-color1);
  font-size: var(--jp-ui-font-size1);
}

/* Disable native link decoration styles everywhere outside of dialog boxes */
a {
  text-decoration: unset;
  color: unset;
}

a:hover {
  text-decoration: unset;
  color: unset;
}

/* Disable default focus outline */
:focus {
  outline: unset;
  outline-offset: unset;
  -moz-outline-radius: unset;
}
```

In here https://github.com/jupyterlab/jupyterlab/blob/master/packages/ui-components/style/base.css#L23

This CSS snippet should probably live in the application packages CSS? The look of a custom web page containing sub-components from JupyterLab packages should probably not be polluted by this CSS snippet.

Any thought?

Happy to open a PR myself doing it.
