### ISSUE TITLE
Remove the dependency on `verdaccio` for `@jupyterlab/builder`

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#13740]
### Problem

Currently extension authors have a dependency on `verdaccio` in their `yarn.lock` because `@jupyterlab/builder` depends on `@jupyterlab/buildutils`, which depends on `verdaccio`:

https://github.com/jupyterlab/jupyterlab/blob/12d1c13dae5f8c4811156c8668b73fd8c1d85318/builder/package.json#L36

https://github.com/jupyterlab/jupyterlab/blob/12d1c13dae5f8c4811156c8668b73fd8c1d85318/buildutils/package.json#L59

### Proposed Solution

Ideally this dependency would be removed or be made optional.

### Additional context

Originally brought by @bollwyvl in https://github.com/jupyterlite/jupyterlite/pull/943#issuecomment-1375672337

**Comment by jtpio** [comment]
After a quick search in the code base it looks like only the `readJSONFile` and `writeJSONFile` helpers from `@jupyterlab/buildutils` are used in `@jupyterlab/builder`:

https://github.com/jupyterlab/jupyterlab/blob/12d1c13dae5f8c4811156c8668b73fd8c1d85318/builder/src/build.ts#L13

https://github.com/jupyterlab/jupyterlab/blob/12d1c13dae5f8c4811156c8668b73fd8c1d85318/builder/src/extensionConfig.ts#L12

**Comment by bollwyvl** [comment]
Thanks for the issue.

As a near term "solution" (though _maybe_ it does't deserve the quotes, as it's built into the package manager), downstreams can avoid installing `verdaccio` (and its vulnerable dependencies) with:

```yaml
# package.json
{
  "resolutions": {
    "verdaccio": "file:_hacks/not-a-package"
  }
}
```

```yaml
#_hacks/not-a-package/package.json
{
  "name": "not-a-package",
  "version": "999.999.999",
  "private": true,
  "description": "a package to avoid installing other packages by file reference in `resolutions`"
}
```

This will remove all of the dependencies of `verdaccio` from `yarn.lock`, but _not_ `verdaccio` itself, so some vuln flags still come up.
