### ISSUE TITLE
M1 Mac local test runs fail with "Library not loaded: '@rpath/libpixman-1.0.dylib'" dependency error

### ISSUE THREAD

**Issue by andrii-i** [jupyterlab/jupyterlab#13938]
## Description

Jupyterlab test runs fail locally with "Library not loaded: '@rpath/libpixman-1.0.dylib'" error. 

- This might be specific to MacOS and/or Apple silicon machines (reproduced on 2 such machines with clean jupyterlab install in fresh conda environment)
- Might be connected to #13783, CC @fcollonval 

<details>
  <summary>Error:</summary>

  ```
  > @jupyterlab/coreutils:test

$ jest
@jupyterlab/coreutils:  FAIL  test/pageconfig.spec.ts
@jupyterlab/coreutils:   ● Test suite failed to run
@jupyterlab/coreutils:     dlopen(/Users/aieroshe/Documents/jupyterlab/node_modules/canvas/build/Release/canvas.node, 0x0001): Library not loaded: '@rpath/libpixman-1.0.dylib'
@jupyterlab/coreutils:       Referenced from: '/Users/aieroshe/Documents/jupyterlab/node_modules/canvas/build/Release/canvas.node'
@jupyterlab/coreutils:       Reason: tried: '/usr/local/lib/libpixman-1.0.dylib' (no such file), '/usr/lib/libpixman-1.0.dylib' (no such file)
@jupyterlab/coreutils:       at Object.<anonymous> (../../node_modules/canvas/lib/bindings.js:3:18)
@jupyterlab/coreutils:  FAIL  test/url.spec.ts
@jupyterlab/coreutils:   ● Test suite failed to run
@jupyterlab/coreutils:     dlopen(/Users/aieroshe/Documents/jupyterlab/node_modules/canvas/build/Release/canvas.node, 0x0001): Library not loaded: '@rpath/libpixman-1.0.dylib'
@jupyterlab/coreutils:       Referenced from: '/Users/aieroshe/Documents/jupyterlab/node_modules/canvas/build/Release/canvas.node'
@jupyterlab/coreutils:       Reason: tried: '/usr/local/lib/libpixman-1.0.dylib' (no such file), '/usr/lib/libpixman-1.0.dylib' (no such file)
@jupyterlab/coreutils:       at Object.<anonymous> (../../node_modules/canvas/lib/bindings.js:3:18)
@jupyterlab/coreutils:  FAIL  test/activitymonitor.spec.ts
@jupyterlab/coreutils:   ● Test suite failed to run
@jupyterlab/coreutils:     dlopen(/Users/aieroshe/Documents/jupyterlab/node_modules/canvas/build/Release/canvas.node, 0x0001): Library not loaded: '@rpath/libpixman-1.0.dylib'
@jupyterlab/coreutils:       Referenced from: '/Users/aieroshe/Documents/jupyterlab/node_modules/canvas/build/Release/canvas.node'
@jupyterlab/coreutils:       Reason: tried: '/usr/local/lib/libpixman-1.0.dylib' (no such file), '/usr/lib/libpixman-1.0.dylib' (no such file)
@jupyterlab/coreutils:       at Object.<anonymous> (../../node_modules/canvas/lib/bindings.js:3:18)
@jupyterlab/coreutils:  FAIL  test/markdowncodeblocks.spec.ts
@jupyterlab/coreutils:   ● Test suite failed to run
@jupyterlab/coreutils:     dlopen(/Users/aieroshe/Documents/jupyterlab/node_modules/canvas/build/Release/canvas.node, 0x0001): Library not loaded: '@rpath/libpixman-1.0.dylib'
@jupyterlab/coreutils:       Referenced from: '/Users/aieroshe/Documents/jupyterlab/node_modules/canvas/build/Release/canvas.node'
@jupyterlab/coreutils:       Reason: tried: '/usr/local/lib/libpixman-1.0.dylib' (no such file), '/usr/lib/libpixman-1.0.dylib' (no such file)
@jupyterlab/coreutils:       at Object.<anonymous> (../../node_modules/canvas/lib/bindings.js:3:18)
@jupyterlab/coreutils:  FAIL  test/path.spec.ts
@jupyterlab/coreutils:   ● Test suite failed to run
@jupyterlab/coreutils:     dlopen(/Users/aieroshe/Documents/jupyterlab/node_modules/canvas/build/Release/canvas.node, 0x0001): Library not loaded: '@rpath/libpixman-1.0.dylib'
@jupyterlab/coreutils:       Referenced from: '/Users/aieroshe/Documents/jupyterlab/node_modules/canvas/build/Release/canvas.node'
@jupyterlab/coreutils:       Reason: tried: '/usr/local/lib/libpixman-1.0.dylib' (no such file), '/usr/lib/libpixman-1.0.dylib' (no such file)
@jupyterlab/coreutils:       at Object.<anonymous> (../../node_modules/canvas/lib/bindings.js:3:18)
@jupyterlab/coreutils:  FAIL  test/time.spec.ts
@jupyterlab/coreutils:   ● Test suite failed to run
@jupyterlab/coreutils:     dlopen(/Users/aieroshe/Documents/jupyterlab/node_modules/canvas/build/Release/canvas.node, 0x0001): Library not loaded: '@rpath/libpixman-1.0.dylib'
@jupyterlab/coreutils:       Referenced from: '/Users/aieroshe/Documents/jupyterlab/node_modules/canvas/build/Release/canvas.node'
@jupyterlab/coreutils:       Reason: tried: '/usr/local/lib/libpixman-1.0.dylib' (no such file), '/usr/lib/libpixman-1.0.dylib' (no such file)
@jupyterlab/coreutils:       at Object.<anonymous> (../../node_modules/canvas/lib/bindings.js:3:18)
@jupyterlab/coreutils: Test Suites: 6 failed, 6 total
@jupyterlab/coreutils: Tests:       0 total
@jupyterlab/coreutils: Snapshots:   0 total
@jupyterlab/coreutils: Time:        0.226 s
  ```
</details>

## Reproduce

1. Attempt to build and run tests as described in ["Build and run tests"](https://jupyterlab.readthedocs.io/en/latest/developer/contributing.html#build-and-run-the-tests) section of the contributing guide, for the whole test suite or for separate package
```
jlpm run build:testutils
jlpm test
```
```
cd packages/notebook
jlpm run build:test
jlpm test --runInBand
```
2. See tests failing with an error described above

## Expected behavior

Test runs go through or fail for valid reason

## Context

Operating System and version: MacOS 12.6.3 Monterey, Apple M1 Pro chip
Browser and version: Chrome version 109.0.5414.87 (Official Build) (arm64)
JupyterLab version: 3.6.x, head-of-master (WIP 4.0.0)

**Comment by krassowski** [comment]
Did you run try running `jlpm` from the root of the repository to refresh node modules? Sometimes errors like this show up when you pull the latest code but do not refresh the node packages. You can also try `jlpm clean` and then `jlpm` What is your node version?

**Comment by andrii-i** [comment]
Thank you for looking into this. Yes, I have tried running `jlpm` in the root, also just tried running `jlpm clean` and then `jlpm` and in both cases error persists. My node version is v19.4.0.

**Comment by krassowski** [comment]
Did you try running a stable Node version like 18.x?

**Comment by andrii-i** [comment]
Switched to 18.14.0 LTS, did a clean install and error still remains.

**Comment by JasonWeill** [comment]
This also occurs for me, on a MacBook Pro with an M1 (Apple Silicon) chip

**Comment by 3coins** [comment]
@andrii-i 
Can you try this installation page, which has instructions to install these packages from source. 
https://github.com/Automattic/node-canvas/wiki/Installation%3A-Mac-OS-X

**Comment by bollwyvl** [comment]
Haters gonna hate, but ol' conda-forge has your back on all of those. A maximally-reproducible `environment.yml` can solve for all of the below:

```bash
conda-lock --file=environment.yml --platform=osx-arm64 --platform=linux-64 --platform=win-64 --platform=osx-64 --kind=explicit
```

```yaml
name: jupyterla-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  # binder
  - jupyterlab-link-share=0.2
  - jupyter_server_fileid
  - jupyter-server-proxy
  - matplotlib-base
  - nodejs=18
  - numpy
  - pip
  - python=3.10
  - vega_datasets
  - xeus-python
  # docs
  - sphinx >=1.8
  - sphinx-copybutton
  - pydata-sphinx-theme
  - pytest
  - pytest-tornasync
  - pytest-check-links
  - jsx-lexer
  - myst-parser
  # screenshots
  - altair
  - ipython
  - ipywidgets
  - jupyterlab-geojson
  - matplotlib-base
  - nbconvert
  - pandas
  - scipy
  - vega_datasets
  # canvas cruft
  - pkgconfig
  - cairo
  - pango
  - libpng
  - libjpeg-turbo
  - giflib
  - librsvg
  - pixman
  # test
  - coverage
  - pytest >=7.0
  - pytest-check-links >=0.7
  - pytest-console-scripts
  - pytest-cov
  - pytest-jupyter >=0.5.3
  - pytest-timeout
  - pytest-tornasync
  - requests
  - requests_cache
  - virtualenv
  # dev
  - build
  - pre-commit
  - pytest-cov
  - coverage
  - hatch
  - bump2version
  - ruff  # ==0.0.242",
  - black-jupyter ==23.1.0
```

At least, it _solves_: good luck doing that with pip/brew/choco!
