### ISSUE TITLE
Set custom CSS, like you could in a Jupyter notebook

### ISSUE THREAD

**Issue by cormullion** [jupyterlab/jupyterlab#14319]
In a Jupyter notebook, you could specify a font by adding some CSS to a file `~/.jupyter/custom/custom.css`. This allowed users to specify a font such as JuliaMono that could correctly handle special characters, and the use of packages such as UnicodePlots.jl.

The default font (Menlo) doesn't have the necessary glyphs, and the replacement glyphs (from Apple Braille) aren't the right width:

![26cdd156e807b76e076c6e79b7fc58e0a785c30e_2_579x500](https://user-images.githubusercontent.com/52289/229461270-f66e8d3e-7c65-43df-89ee-3bc14888f43c.png)

It should be easy to specify the font family using CSS, allowing the display to be rendered correctly, as here in Jupyter notebook.

![3926ddf4c1bd2caecf2eb3b880ad9d2b41fedc71_2_690x311](https://user-images.githubusercontent.com/52289/229461943-265c1624-4b88-4d3b-9eaf-bffc46fdab4b.png)

**Comment by cormullion** [comment]
I didn't try that - I couldn't see where to insert the:

```css
@font-face {
    font-family: JuliaMono-Light;
    src: url("https://cdn.jsdelivr.net/gh/cormullion/juliamono/webfonts/JuliaMono-Light.woff2");
}
```
or similar CSS instructions...
