### ISSUE TITLE
Missing __init__.py file and hyphens in name for extension leads to a broken build

### ISSUE THREAD

**Issue by caleb-at-pieces** [jupyterlab/jupyterlab#15603]
## Description

I develop a jupyterlab extension and recently pushed a release (~December 22nd)

Nothing changed too much in the dependencies besides adding jupyterlab/terminal as a dependency as well as some nested dep's got bumped a patch or two.

The extension is no longer able to be installed by jupyterlab. When running `pip install jupyter-pieces`, it creates a jupyter-pieces directory in my extensions folder however it only contains install.json and not the rest of the static files.

Upon debugging this I have found that there are two reasons for this problem:

1. a missing `__init__.py` file in /jupyter_pieces/labextension
2. changing the name of my package from jupyter-pieces to jupyter_pieces

## Reproduce

1. create a labextension project
2. either 1: delete the generated `__init__.py` file or introduce hyphens into the extension name
3. the .whl file generated by `python3 -m build` does not include any of the static build files required to run & install the extension

## Expected behavior

I expect that you should be able to have hyphens in an extension name, and that if the `__init__.py` file is missing, there should be an error thrown in the build step, or a new `__init__.py` file should be generated at build time instead of silently failing.

## Context

- Operating System and version: 13.4.1 (c)  mac os arm 
- Browser and version: chrome Version 120.0.6099.199 (Official Build) (arm64)
- JupyterLab version: 4.0.10

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
	/Users/calebanderson/Documents/ngrok
	/Users/calebanderson/Documents/google-cloud-sdk/bin
	/Users/calebanderson/.nvm/versions/node/v20.3.0/bin
	/Users/calebanderson/anaconda3/envs/test-1.8.2/bin
	/Users/calebanderson/anaconda3/condabin
	/Library/Frameworks/Python.framework/Versions/3.11/bin
	/opt/homebrew/bin
	/opt/homebrew/sbin
	/usr/local/bin
	/System/Cryptexes/App/usr/bin
	/usr/bin
	/bin
	/usr/sbin
	/sbin
	/Library/Apple/usr/bin
	/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin
	/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin
	/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
	/Users/calebanderson/Documents/flutter/bin

sys.path:
	/Library/Frameworks/Python.framework/Versions/3.11/bin
	/Library/Frameworks/Python.framework/Versions/3.11/lib/python311.zip
	/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11
	/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload
	/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages
	/Users/calebanderson/Documents/plugin_jupyter

sys.executable:
	/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11

sys.version:
	3.11.3 (v3.11.3:f3909b8bc8, Apr  4 2023, 20:12:10) [Clang 13.0.0 (clang-1300.0.29.30)]

platform.platform():
	macOS-13.4.1-arm64-arm-64bit

which -a jupyter:
	/Library/Frameworks/Python.framework/Versions/3.11/bin/jupyter

pip list:
	Package                   Version    Editable project location
	------------------------- ---------- ---------------------------------------------
	aiofiles                  22.1.0
	aiosqlite                 0.19.0
	anyio                     4.2.0
	appnope                   0.1.3
	argon2-cffi               23.1.0
	argon2-cffi-bindings      21.2.0
	arrow                     1.3.0
	asttokens                 2.4.1
	async-lru                 2.0.4
	attrs                     23.2.0
	Babel                     2.14.0
	backcall                  0.2.0
	beautifulsoup4            4.12.2
	bleach                    6.1.0
	build                     1.0.3
	certifi                   2023.11.17
	cffi                      1.16.0
	charset-normalizer        3.3.2
	comm                      0.2.1
	contourpy                 1.1.0
	cycler                    0.11.0
	debugpy                   1.8.0
	decorator                 5.1.1
	defusedxml                0.7.1
	docutils                  0.20.1
	executing                 2.0.1
	fastjsonschema            2.19.1
	fonttools                 4.40.0
	fqdn                      1.5.1
	idna                      3.6
	importlib-metadata        6.8.0
	ipykernel                 6.28.0
	ipython                   8.19.0
	ipython-genutils          0.2.0
	ipywidgets                8.1.1
	isoduration               20.11.0
	jaraco.classes            3.3.0
	jedi                      0.19.1
	Jinja2                    3.1.2
	json5                     0.9.14
	jsonpointer               2.4
	jsonschema                4.20.0
	jsonschema-specifications 2023.12.1
	jupyter                   1.0.0
	jupyter_client            8.6.0
	jupyter-console           6.6.3
	jupyter_core              5.7.0
	jupyter-events            0.9.0
	jupyter-lsp               2.2.1
	jupyter-pieces            1.9.0      /Users/calebanderson/Documents/plugin_jupyter
	jupyter_server            2.12.1
	jupyter_server_fileid     0.9.0
	jupyter_server_terminals  0.5.1
	jupyter_server_ydoc       0.8.0
	jupyter-ydoc              0.2.4
	jupyterlab                4.0.10
	jupyterlab_pygments       0.3.0
	jupyterlab_server         2.25.2
	jupyterlab-widgets        3.0.9
	keyring                   24.2.0
	kiwisolver                1.4.4
	markdown-it-py            3.0.0
	MarkupSafe                2.1.3
	matplotlib                3.7.1
	matplotlib-inline         0.1.6
	mdurl                     0.1.2
	mistune                   3.0.2
	more-itertools            10.1.0
	nbclassic                 1.0.0
	nbclient                  0.9.0
	nbconvert                 7.14.0
	nbformat                  5.9.2
	nest-asyncio              1.5.8
	networkx                  3.1
	nh3                       0.2.14
	notebook                  7.0.6
	notebook_shim             0.2.3
	numpy                     1.24.3
	overrides                 7.4.0
	packaging                 23.2
	pandocfilters             1.5.0
	parso                     0.8.3
	pexpect                   4.9.0
	pickleshare               0.7.5
	Pillow                    9.5.0
	pip                       23.3.2
	pkginfo                   1.9.6
	platformdirs              4.1.0
	prometheus-client         0.19.0
	prompt-toolkit            3.0.43
	psutil                    5.9.7
	ptyprocess                0.7.0
	pure-eval                 0.2.2
	pycparser                 2.21
	Pygments                  2.17.2
	pyparsing                 3.0.9
	pyproject_hooks           1.0.0
	pyrsistent                0.19.3
	python-dateutil           2.8.2
	python-json-logger        2.0.7
	PyYAML                    6.0.1
	pyzmq                     25.1.2
	qtconsole                 5.5.0
	QtPy                      2.4.1
	readme-renderer           42.0
	referencing               0.32.0
	requests                  2.31.0
	requests-toolbelt         1.0.0
	rfc3339-validator         0.1.4
	rfc3986                   2.0.0
	rfc3986-validator         0.1.1
	rich                      13.6.0
	rpds-py                   0.16.2
	Send2Trash                1.8.2
	setuptools                68.2.2
	six                       1.16.0
	sniffio                   1.3.0
	soupsieve                 2.5
	stack-data                0.6.3
	terminado                 0.18.0
	tinycss2                  1.2.1
	tornado                   6.4
	traitlets                 5.14.1
	twine                     4.0.2
	types-python-dateutil     2.8.19.14
	typing_extensions         4.5.0
	uri-template              1.3.0
	urllib3                   2.1.0
	wcwidth                   0.2.12
	webcolors                 1.13
	webencodings              0.5.1
	websocket-client          1.7.0
	wheel                     0.41.3
	widgetsnbextension        4.0.9
	y-py                      0.5.9
	ypy-websocket             0.8.2
	zipp                      3.17.0

conda list:
	# packages in environment at /Users/calebanderson/anaconda3/envs/test-1.8.2:
	#
	# Name                    Version                   Build  Channel

conda env:
	name: test-1.8.2
	channels:
	  - defaults
	prefix: /Users/calebanderson/anaconda3/envs/test-1.8.2
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
[W 2024-01-03 17:23:45.338 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[W 2024-01-03 17:23:45.350 ServerApp] A `_jupyter_server_extension_points` function was not found in nbclassic. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[W 2024-01-03 17:23:45.351 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2024-01-03 17:23:45.352 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-01-03 17:23:45.353 ServerApp] jupyter_server_fileid | extension was successfully linked.
[I 2024-01-03 17:23:45.354 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-01-03 17:23:45.356 ServerApp] jupyter_server_ydoc | extension was successfully linked.
[I 2024-01-03 17:23:45.357 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-01-03 17:23:45.359 ServerApp] nbclassic | extension was successfully linked.
[I 2024-01-03 17:23:45.360 ServerApp] notebook | extension was successfully linked.
[I 2024-01-03 17:23:45.445 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-01-03 17:23:45.458 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-01-03 17:23:45.459 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-01-03 17:23:45.459 FileIdExtension] Configured File ID manager: ArbitraryFileIdManager
[I 2024-01-03 17:23:45.460 FileIdExtension] ArbitraryFileIdManager : Configured root dir: /Users/calebanderson
[I 2024-01-03 17:23:45.460 FileIdExtension] ArbitraryFileIdManager : Configured database path: /Users/calebanderson/Library/Jupyter/file_id_manager.db
[I 2024-01-03 17:23:45.460 FileIdExtension] ArbitraryFileIdManager : Successfully connected to database file.
[I 2024-01-03 17:23:45.460 FileIdExtension] ArbitraryFileIdManager : Creating File ID tables and indices with journal_mode = DELETE
[I 2024-01-03 17:23:45.460 FileIdExtension] Attached event listeners.
[I 2024-01-03 17:23:45.460 ServerApp] jupyter_server_fileid | extension was successfully loaded.
[I 2024-01-03 17:23:45.460 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-01-03 17:23:45.461 ServerApp] jupyter_server_ydoc | extension was successfully loaded.
[I 2024-01-03 17:23:45.462 LabApp] JupyterLab extension loaded from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/jupyterlab
[I 2024-01-03 17:23:45.462 LabApp] JupyterLab application directory is /Library/Frameworks/Python.framework/Versions/3.11/share/jupyter/lab
[I 2024-01-03 17:23:45.462 LabApp] Extension Manager is 'pypi'.
[I 2024-01-03 17:23:45.463 ServerApp] jupyterlab | extension was successfully loaded.

  _   _          _      _
 | | | |_ __  __| |__ _| |_ ___
 | |_| | '_ \/ _` / _` |  _/ -_)
  \___/| .__/\__,_\__,_|\__\___|
       |_|
                                                                           
Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.

https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html

Please note that updating to Notebook 7 might break some of your extensions.

[I 2024-01-03 17:23:45.464 ServerApp] nbclassic | extension was successfully loaded.
[I 2024-01-03 17:23:45.465 ServerApp] notebook | extension was successfully loaded.
[I 2024-01-03 17:23:45.466 ServerApp] Serving notebooks from local directory: /Users/calebanderson
[I 2024-01-03 17:23:45.466 ServerApp] Jupyter Server 2.12.1 is running at:
[I 2024-01-03 17:23:45.466 ServerApp] http://localhost:8888/lab?token=3df4cbcc5f8f8335f6afb5c1a40ee301bbe3f7632a45a4a5
[I 2024-01-03 17:23:45.466 ServerApp]     http://127.0.0.1:8888/lab?token=3df4cbcc5f8f8335f6afb5c1a40ee301bbe3f7632a45a4a5
[I 2024-01-03 17:23:45.466 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2024-01-03 17:23:45.467 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///Users/calebanderson/Library/Jupyter/runtime/jpserver-11962-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=3df4cbcc5f8f8335f6afb5c1a40ee301bbe3f7632a45a4a5
        http://127.0.0.1:8888/lab?token=3df4cbcc5f8f8335f6afb5c1a40ee301bbe3f7632a45a4a5
[I 2024-01-03 17:23:45.698 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
</pre>
</details>

**Comment by krassowski** [comment]
Quickly looking at https://pypi.org/project/jupyter-pieces/1.8.1/#files vs https://pypi.org/project/jupyter-pieces/1.9.0/#files it strikes me that the wheel distribution for 1.9.0 is only 6.5 kB compared to the wheel for 1.8.1 which was 3.2 MB, so the problem is not at the installation but at the packaging stage.

To understand what is your setup and what to suggest, let me ask:
- are you using jupyter-packaging, hatch, or a different packaging tool?
- did you migrate the extension using our extension template to a new version?
- are your wheels built in isolation? If not, could it be that two attempts to create artefacts clashed resulting in one being empty?
- do you use a MANIFEST file?
- does installation from source (`pip install jupyter-pieces --no-binary=jupyter-pieces`) works?
- are there any relevant logs from the packaging process that you could share (e.g from running `python -m build` assuming you use PEP 517)?

**Comment by caleb-at-pieces** [comment]
> Quickly looking at https://pypi.org/project/jupyter-pieces/1.8.1/#files vs https://pypi.org/project/jupyter-pieces/1.9.0/#files it strikes me that the wheel distribution for 1.9.0 is only 6.5 kB compared to the wheel for 1.8.1 which was 3.2 MB, so the problem is not at the installation but at the packaging stage.
> 
> To understand what is your setup and what to suggest, let me ask:
> 
> * are you using jupyter-packaging, hatch, or a different packaging tool?
> * did you migrate the extension using our extension template to a new version?
> * are your wheels built in isolation? If not, could it be that two attempts to create artefacts clashed resulting in one being empty?
> * do you use a MANIFEST file?
> * does installation from source (`pip install jupyter-pieces --no-binary=jupyter-pieces`) works?
> * are there any relevant logs from the packaging process that you could share (e.g from running `python -m build` assuming you use PEP 517)?

1. Running `python3 -m build` it appears that it is using hatch (I gave the logs for this command below)
2. The extension never needed a migration, we began development at pretty much the same time that Jupyter Lab 4.0.0 was released
3. The dist is built within a GitHub runner so yes it is ephemeral, and it only builds one package at a time.
4. I don’t know much about a MANIFEST file, so I’m assuming we don’t use one.
5. Installing from source seems to have the same exact behavior, with only the install.json being present within the Jupyter-pieces directory of my lab extensions directory
6. I don’t see any relevant logs running python -m build, yes this is how we build the extension. Comparing to previous builds it is the exact same, I can share below:

Another comment here, if I manually move my source files (schema, static, build_log.json, package.json) into the lab extensions directory (/path/to/labextensions/jupyter-pieces), everything seems to work fine.

```
* Creating venv isolated environment...
* Installing packages in isolated environment... (hatch-nodejs-version, hatchling>=1.5.0, jupyterlab>=4.0.0,<5)
* Getting build dependencies for sdist...
* Installing packages in isolated environment... (hatch-jupyter-builder>=0.5)
* Building sdist...
INFO:hatch_jupyter_builder.utils:Running jupyter-builder
INFO:hatch_jupyter_builder.utils:Skip-if-exists file(s) found
INFO:hatch_jupyter_builder.utils:Skipping build
INFO:hatch_jupyter_builder.utils:Ensured target(s) exist!
INFO:hatch_jupyter_builder.utils:Finished running jupyter-builder
* Building wheel from sdist
* Creating venv isolated environment...
* Installing packages in isolated environment... (hatch-nodejs-version, hatchling>=1.5.0, jupyterlab>=4.0.0,<5)
* Getting build dependencies for wheel...
* Installing packages in isolated environment... (hatch-jupyter-builder>=0.5)
* Building wheel...
INFO:hatch_jupyter_builder.utils:Running jupyter-builder
INFO:hatch_jupyter_builder.utils:Skip-if-exists file(s) found
INFO:hatch_jupyter_builder.utils:Skipping build
INFO:hatch_jupyter_builder.utils:Ensured target(s) exist!
INFO:hatch_jupyter_builder.utils:Finished running jupyter-builder
Successfully built jupyter_pieces-1.9.0.tar.gz and jupyter_pieces-1.9.0-py3-none-any.whl
```

**Comment by caleb-at-pieces** [comment]
Small update from my end: I took the liberty to go and rerun a build from several months ago on a GH runner and am seeing the same result: a 4kb .whl file (instead of some megabytes).

**Comment by caleb-at-pieces** [comment]
My work today narrowing this down I have found that the issue is somewhere in my pyproject.toml file:

this is the broken toml file
```toml
[build-system]
requires = ["hatchling>=1.5.0", "jupyterlab>=4.0.0,<5", "hatch-nodejs-version"]
build-backend = "hatchling.build"

[project]
name = "jupyter-pieces"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
classifiers = [
    "Framework :: Jupyter",
    "Framework :: Jupyter :: JupyterLab",
    "Framework :: Jupyter :: JupyterLab :: 4",
    "Framework :: Jupyter :: JupyterLab :: Extensions",
    "Framework :: Jupyter :: JupyterLab :: Extensions :: Prebuilt",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
]
dynamic = ["version", "description", "authors", "urls", "keywords"]

[tool.hatch.version]
source = "nodejs"

[tool.hatch.metadata.hooks.nodejs]
fields = ["description", "authors", "urls"]

[tool.hatch.build.targets.sdist]
artifacts = ["jupyter-pieces/labextension"]
exclude = [".github", "binder"]

[tool.hatch.build.targets.wheel.shared-data]
"jupyter-pieces/labextension" = "share/jupyter/labextensions/jupyter-pieces"
"install.json" = "share/jupyter/labextensions/jupyter-pieces/install.json"

[tool.hatch.build.hooks.version]
path = "jupyter-pieces/_version.py"

[tool.hatch.build.hooks.jupyter-builder]
dependencies = ["hatch-jupyter-builder>=0.5"]
build-function = "hatch_jupyter_builder.npm_builder"
ensured-targets = [
    "jupyter-pieces/labextension/static/style.js",
    "jupyter-pieces/labextension/package.json",
]
skip-if-exists = ["jupyter-pieces/labextension/static/style.js"]

[tool.hatch.build.hooks.jupyter-builder.build-kwargs]
build_cmd = "build:prod"
npm = ["jlpm"]

[tool.hatch.build.hooks.jupyter-builder.editable-build-kwargs]
build_cmd = "install:extension"
npm = ["jlpm"]
source_dir = "src"
build_dir = "jupyter-pieces/labextension"

[tool.jupyter-releaser.options]
version_cmd = "hatch version"

[tool.jupyter-releaser.hooks]
before-build-npm = [
    "python -m pip install 'jupyterlab>=4.0.0,<5'",
    "jlpm",
    "jlpm build:prod"
]
before-build-python = ["jlpm clean:all"]

[tool.check-wheel-contents]
ignore = ["W002"]
```

this file is working
```toml
[build-system]
requires = ["hatchling>=1.5.0", "jupyterlab>=4.0.0,<5", "hatch-nodejs-version>=0.3.2"]
build-backend = "hatchling.build"

[project]
name = "jupyterlab_examples_hello_world"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
classifiers = [
    "Framework :: Jupyter",
    "Framework :: Jupyter :: JupyterLab",
    "Framework :: Jupyter :: JupyterLab :: 4",
    "Framework :: Jupyter :: JupyterLab :: Extensions",
    "Framework :: Jupyter :: JupyterLab :: Extensions :: Prebuilt",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
]
dynamic = ["version", "description", "authors", "urls", "keywords"]

[tool.hatch.version]
source = "nodejs"

[tool.hatch.metadata.hooks.nodejs]
fields = ["description", "authors", "urls"]

[tool.hatch.build.targets.sdist]
artifacts = ["jupyterlab_examples_hello_world/labextension"]
exclude = [".github", "binder"]

[tool.hatch.build.targets.wheel.shared-data]
"jupyterlab_examples_hello_world/labextension" = "share/jupyter/labextensions/@jupyterlab-examples/hello-world"
"install.json" = "share/jupyter/labextensions/@jupyterlab-examples/hello-world/install.json"

[tool.hatch.build.hooks.version]
path = "jupyterlab_examples_hello_world/_version.py"

[tool.hatch.build.hooks.jupyter-builder]
dependencies = ["hatch-jupyter-builder>=0.5"]
build-function = "hatch_jupyter_builder.npm_builder"
ensured-targets = [
    "jupyterlab_examples_hello_world/labextension/static/style.js",
    "jupyterlab_examples_hello_world/labextension/package.json",
]
skip-if-exists = ["jupyterlab_examples_hello_world/labextension/static/style.js"]

[tool.hatch.build.hooks.jupyter-builder.build-kwargs]
build_cmd = "build:prod"
npm = ["jlpm"]

[tool.hatch.build.hooks.jupyter-builder.editable-build-kwargs]
build_cmd = "install:extension"
npm = ["jlpm"]
source_dir = "src"
build_dir = "jupyterlab_examples_hello_world/labextension"

[tool.jupyter-releaser.options]
version_cmd = "hatch version"

[tool.jupyter-releaser.hooks]
before-build-npm = [
    "python -m pip install 'jupyterlab>=4.0.0,<5'",
    "jlpm",
    "jlpm build:prod"
]
before-build-python = ["jlpm clean:all"]

[tool.check-wheel-contents]
ignore = ["W002"]
```

Still trying to narrow down what exactly is the problem that is causing this.
