### ISSUE TITLE
None of the docker images for Jupyter working

### ISSUE THREAD

**Issue by encryptblockr** [jupyterlab/jupyterlab#17055]
## Description

I am trying to setup the following jupyter based on these images, i have tried all 3 and yet same issues
I am super shocked how the entire internet does not have this reported or documented how to run jupyter with these images

- image: quay.io/jupyter/pyspark-notebook:spark-3.5.3
- quay.io/jupyter/all-spark-notebook:spark-3.5.3
- quay.io/jupyter/base-notebook:python-3.12.7

## Reproduce

Just try to run jupyter with these images, it does not work!!!
her eis sample docker compose/swarm yaml i used, i removed everything and made it basic setup and still same annoying Signal 15 Update notebook 7 annoying useless error 

```
  jupyter1:
    image: quay.io/jupyter/pyspark-notebook:spark-3.5.3
    networks:
      - apps
    deploy:
      placement:
        constraints:
          - node.labels.node == dev-1
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=apps"
        - "traefik.http.services.jupyter1.loadbalancer.server.port=8888"
        - "traefik.http.routers.jupyter1-http.entrypoints=http"
        - "traefik.http.routers.jupyter1-http.rule=Host(`jupyter1.apps`)"
        
  jupyter2:
    image: quay.io/jupyter/all-spark-notebook:spark-3.5.3
    networks:
      - apps
    deploy:
      placement:
        constraints:
          - node.labels.node == dev-1
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=apps"
        - "traefik.http.services.jupyter2.loadbalancer.server.port=8888"
        - "traefik.http.routers.jupyter2-http.entrypoints=http"
        - "traefik.http.routers.jupyter2-http.rule=Host(`jupyter2.apps`)"
```

> error logs

```
Entered start.sh with args: start-notebook.py
Running hooks in: /usr/local/bin/start-notebook.d as uid: 1000 gid: 100
Done running hooks in: /usr/local/bin/start-notebook.d
Running hooks in: /usr/local/bin/before-notebook.d as uid: 1000 gid: 100
Sourcing shell script: /usr/local/bin/before-notebook.d/10activate-conda-env.sh
Sourcing shell script: /usr/local/bin/before-notebook.d/10spark-config.sh
Done running hooks in: /usr/local/bin/before-notebook.d
Executing the command: start-notebook.py
[I 2024-12-08 12:57:52.432 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-12-08 12:57:52.453 ServerApp] jupyter_server_mathjax | extension was successfully linked.
[I 2024-12-08 12:57:52.473 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-12-08 12:57:52.495 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-12-08 12:57:52.495 ServerApp] jupyterlab_git | extension was successfully linked.
[I 2024-12-08 12:57:52.512 ServerApp] nbclassic | extension was successfully linked.
[I 2024-12-08 12:57:52.513 ServerApp] nbdime | extension was successfully linked.
[I 2024-12-08 12:57:52.535 ServerApp] notebook | extension was successfully linked.
[I 2024-12-08 12:57:52.541 ServerApp] Writing Jupyter server cookie secret to /home/jovyan/.local/share/jupyter/runtime/jupyter_cookie_secret
[I 2024-12-08 12:57:53.592 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-12-08 12:57:53.661 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-12-08 12:57:53.668 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-12-08 12:57:53.669 ServerApp] jupyter_server_mathjax | extension was successfully loaded.
[I 2024-12-08 12:57:53.673 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-12-08 12:57:53.682 LabApp] JupyterLab extension loaded from /opt/conda/lib/python3.11/site-packages/jupyterlab
[I 2024-12-08 12:57:53.683 LabApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 2024-12-08 12:57:53.684 LabApp] Extension Manager is 'pypi'.
[I 2024-12-08 12:57:53.734 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-12-08 12:57:53.750 ServerApp] jupyterlab_git | extension was successfully loaded.
[I 2024-12-08 12:57:53.763 ServerApp] nbclassic | extension was successfully loaded.
[I 2024-12-08 12:57:53.986 ServerApp] nbdime | extension was successfully loaded.
[I 2024-12-08 12:57:54.003 ServerApp] notebook | extension was successfully loaded.
[I 2024-12-08 12:57:54.004 ServerApp] Serving notebooks from local directory: /home/jovyan
[I 2024-12-08 12:57:54.005 ServerApp] Jupyter Server 2.12.5 is running at:
[I 2024-12-08 12:57:54.005 ServerApp] http://93779934cf3b:8888/lab?token=28db034c39a9cc50eb0709c7c30e82a98228a7b3e30587c1
[I 2024-12-08 12:57:54.005 ServerApp]     http://127.0.0.1:8888/lab?token=28db034c39a9cc50eb0709c7c30e82a98228a7b3e30587c1
[I 2024-12-08 12:57:54.005 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2024-12-08 12:57:54.018 ServerApp] To access the server, open this file in a browser:
file:///home/jovyan/.local/share/jupyter/runtime/jpserver-7-open.html
Or copy and paste one of these URLs:
http://93779934cf3b:8888/lab?token=28db034c39a9cc50eb0709c7c30e82a98228a7b3e30587c1
http://127.0.0.1:8888/lab?token=28db034c39a9cc50eb0709c7c30e82a98228a7b3e30587c1
[I 2024-12-08 12:57:57.099 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[C 2024-12-08 12:58:12.624 ServerApp] received signal 15, stopping
[I 2024-12-08 12:58:12.627 ServerApp] Shutting down 9 extensions
  _   _          _      _
 | | | |_ __  __| |__ _| |_ ___
 | |_| | '_ \/ _` / _` |  _/ -_)
  \___/| .__/\__,_\__,_|\__\___|
       |_|
Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.
https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html
Please note that updating to Notebook 7 might break some of your extensions.
```

> jupyter3

```
  jupyter3:
    image: quay.io/jupyter/base-notebook:python-3.12.7
    user: root
    networks:
      - apps
    environment:
       - NB_UID=1000
       - NB_GID=1000
       - NOTEBOOK_ARGS='--allow-root'
    deploy:
      placement:
        constraints:
          - node.labels.node == dev-1
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=apps"
        - "traefik.http.services.jupyter3.loadbalancer.server.port=8888"
        - "traefik.http.routers.jupyter3-http.entrypoints=http"
        - "traefik.http.routers.jupyter3-http.rule=Host(`jupyter3.apps`)"
```

> jupyter 3 errors

```
Entered start.sh with args: start-notebook.py
Running hooks in: /usr/local/bin/start-notebook.d as uid: 0 gid: 0
Done running hooks in: /usr/local/bin/start-notebook.d
Update jovyan's UID:GID to 1000:1000
userdel: group jovyan not removed because it is not the primary group of user jovyan.
Running hooks in: /usr/local/bin/before-notebook.d as uid: 0 gid: 0
Sourcing shell script: /usr/local/bin/before-notebook.d/10activate-conda-env.sh
Done running hooks in: /usr/local/bin/before-notebook.d
Running as jovyan: start-notebook.py
[I 2024-12-08 12:41:30.243 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-12-08 12:41:30.261 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-12-08 12:41:30.292 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-12-08 12:41:30.310 ServerApp] nbclassic | extension was successfully linked.
[I 2024-12-08 12:41:30.332 ServerApp] notebook | extension was successfully linked.
[I 2024-12-08 12:41:30.338 ServerApp] Writing Jupyter server cookie secret to /home/jovyan/.local/share/jupyter/runtime/jupyter_cookie_secret
[I 2024-12-08 12:41:31.396 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-12-08 12:41:31.489 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-12-08 12:41:31.500 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-12-08 12:41:31.505 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-12-08 12:41:31.512 LabApp] JupyterLab extension loaded from /opt/conda/lib/python3.12/site-packages/jupyterlab
[I 2024-12-08 12:41:31.512 LabApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 2024-12-08 12:41:31.514 LabApp] Extension Manager is 'pypi'.
[W 2024-12-08 12:41:31.516 LabApp] Failed to instantiate the extension manager pypi. Falling back to read-only manager.
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.12/site-packages/jupyterlab/labapp.py", line 837, in initialize_handlers
        ext_manager = manager_factory(app_options, listings_config, self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.12/site-packages/jupyterlab/extensions/__init__.py", line 46, in get_pypi_manager
        return PyPIExtensionManager(app_options, ext_options, parent)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.12/site-packages/jupyterlab/extensions/pypi.py", line 134, in __init__
        self._httpx_client = httpx.AsyncClient(proxies=proxies)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    TypeError: AsyncClient.__init__() got an unexpected keyword argument 'proxies'
[I 2024-12-08 12:41:31.541 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-12-08 12:41:31.557 ServerApp] nbclassic | extension was successfully loaded.
[I 2024-12-08 12:41:31.576 ServerApp] notebook | extension was successfully loaded.
[I 2024-12-08 12:41:31.578 ServerApp] Serving notebooks from local directory: /home/jovyan
[I 2024-12-08 12:41:31.578 ServerApp] Jupyter Server 2.14.2 is running at:
[I 2024-12-08 12:41:31.578 ServerApp] http://70e4a345c7bb:8888/lab?token=f713140bdb4d3a604d69cd66009e9edd5d81b38473ac308f
[I 2024-12-08 12:41:31.578 ServerApp]     http://127.0.0.1:8888/lab?token=f713140bdb4d3a604d69cd66009e9edd5d81b38473ac308f
[I 2024-12-08 12:41:31.579 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2024-12-08 12:41:31.594 ServerApp] 
    To access the server, open this file in a browser:
        file:///home/jovyan/.local/share/jupyter/runtime/jpserver-47-open.html
    Or copy and paste one of these URLs:
        http://70e4a345c7bb:8888/lab?token=f713140bdb4d3a604d69cd66009e9edd5d81b38473ac308f
        http://127.0.0.1:8888/lab?token=f713140bdb4d3a604d69cd66009e9edd5d81b38473ac308f
[I 2024-12-08 12:41:31.708 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[C 2024-12-08 12:41:39.672 ServerApp] received signal 15, stopping
[C 2024-12-08 12:41:39.673 ServerApp] received signal 15, stopping
[I 2024-12-08 12:41:39.675 ServerApp] Shutting down 6 extensions
[I 2024-12-08 12:41:39.677 ServerApp] Shutting down 6 extensions
  _   _          _      _
 | | | |_ __  __| |__ _| |_ ___
 | |_| | '_ \/ _` / _` |  _/ -_)
  \___/| .__/\__,_\__,_|\__\___|
       |_| 
Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.
https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html
Please note that updating to Notebook 7 might break some of your extensions

```

all of these same similar error, with zero doc a=or online resource to help show solution to this annoying error
by default container should just work but not with jupyter

```
[I 2024-12-08 12:41:31.708 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[C 2024-12-08 12:41:39.672 ServerApp] received signal 15, stopping
[C 2024-12-08 12:41:39.673 ServerApp] received signal 15, stopping
[I 2024-12-08 12:41:39.675 ServerApp] Shutting down 6 extensions
[I 2024-12-08 12:41:39.677 ServerApp] Shutting down 6 extensions
  _   _          _      _
 | | | |_ __  __| |__ _| |_ ___
 | |_| | '_ \/ _` / _` |  _/ -_)
  \___/| .__/\__,_\__,_|\__\___|
       |_| 
Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.
https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html
Please note that updating to Notebook 7 might break some of your extensions
```

## Expected behavior

Running jupyter containers without errors

## Context

```
- image: quay.io/jupyter/pyspark-notebook:spark-3.5.3
- quay.io/jupyter/all-spark-notebook:spark-3.5.3
- quay.io/jupyter/base-notebook:python-3.12.7
```

```
root@server:~# docker version
Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:40:59 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:40:59 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.22
  GitCommit:        7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc:
  Version:          1.1.14
  GitCommit:        v1.1.14-0-g2c9f560
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
  
  
root@server:~# docker compose version
Docker Compose version v2.29.7
```

## What I Need Help With?

a docker-compose or docker run command with the images that will run jupyter notebook with zero errors

Thanks!
