### ISSUE TITLE
Allow editors to register for specific file name patterns

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlab/jupyterlab#2414]
A number of structured files have standard extensions, but community-specific names with special meanings:
- `jupyter_notebook_config.json`
- `package.json`
- `meta.yaml`
- `environment.yml`
- `requirements.txt`
- `docker-compose.yml`
- `tsconfig.json`
- `MANIFEST.in`
- `setup.cfg`

For many of those, there are canonical representations (JSON Schema, PEG) which could provide lots of value:
- linting 
- autocomplete
- inspector content

These can't be matched with the current mechanisms (i.e. has to start with period, etc). Something that 
```ts
  const factory = new DockerComposeFactory({
    name: 'Docker Compose',
    fileExtensions: ['.yml', '.yaml'],
    defaultForPatterns:  [/docker-compose.*\.ya?ml$/]
  });
```

Paired with serverextensions, these could provide tremendous value: 
```yml
# docker-compose.yml
services:
  foo:                  _______________________
    image: jupyter/   <  jupyterhub 78⭐ / 1M⬇️ |
                       | jupyterhub 80⭐ / 5K⬇️ |
                       | ...                   |
                        -----------------------                       
```

These would also be nice to be able to modify from the defaults in settings for a plugin!
