### ISSUE TITLE
Running anaconda-project prepare causes segfault in safari

### ISSUE THREAD

**Issue by birdsarah** [jupyterlab/jupyterlab#2905]
Steps to reproduce

1) Create environment
```bash
$ conda create -n jupyterlab_test_prepare python=3.6 anaconda-project=0.8.0 jupyterlab -c anaconda-platform
$ source activate jupyterlab_test_prepare
$ jupyter lab --no-browser
```

2) Navigate to jupyterlab in safari

3) Create a file `anaconda-project.yml`

```yaml
name: Anaconda 3

packages:
- anaconda=4.4.0
- python>=3.6,<3.7

platforms:
- linux-64
- osx-64
- win-64

env_specs:
  default:
    packages: []
    channels: []
```

3) Open terminal

4) confirm `anaconda-project --version` is 0.8.0

5) anaconda-project prepare 

Safari usually crashes around here - but it does vary:

<img width="1165" alt="screen shot 2017-08-23 at 3 48 19 pm" src="https://user-images.githubusercontent.com/1796208/29635957-da145a56-881c-11e7-8ba3-91dfa06d5c51.png">

If all the packages are cached then sometimes it doesn't crash. In that case, I do `rm -rf ~/miniconda3/pkgs`
