### ISSUE TITLE
line wrapping and backticks

### ISSUE THREAD

**Issue by scubahub** [jupyterlab/jupyterlab#3186]
With a markdown cell with a lot of text and embedded code (via triple backticks), I find the line wrapping behavior when you resize the browser window to be unexpected.  The text portion will change line wrapping normally (both growing and shrinking) so long as you do not try to make the window less wide than the longest code line.  Once the window width gets near the end of the longest code line, line wrapping of the non code portion of the cell stops happening.  I would not expect the code to be wrapped, but do expect the text to keep wrapping as you make the window smaller.

To reproduce, make a notebook with several markdown cells.
First cell:
--- content start (copy the raw markdown) ---
# Example 1
Text with embedded code via tripple backticks.

Saltstack pillar is also a database of information that can 
be referenced from state sls yaml files.  Pillar is data hosted 
on the master that is conditionally made available in the context 
of state execution on a particular minion.  Unlike grains, pillar data may change frequently.

Like state sls files, pillar files are yaml files with a `.sls` extension 
that by default utilize jinja as a templating engine.  Here is an example 
of an actual pillar file:

```
{%- set igroup = salt["grains.get"]("igroup") %}
{%- set sector = salt["grains.get"]("sector") %}

archiver:
  enriched:
    s3-bucket: {{ igroup }}.com.shpsec.{{ sector }}.sds-archiver.enriched
    kafka-enabled: true
    output:
      filehandler:
        remove_envelope_header: false

td-agent:
  sources:
    sds-enriched-aws-archiver:
      type: "tail"
      format: "none"
      path: "/opt/app/var/log/sds-enriched-aws-archiver/enriched-aws-archiver.log"
      pos_file: "/opt/app/td-agent/pos/sds-enriched-aws-archiver.pos"
      read_from_head: "true"
      tag: "sds-enriched-aws-archiver"
```
--- content end ---

Second cell:
--- content start (copy the raw markdown) ---
# Example 2
This time breaking the code block out into a separate markdown cell.

Saltstack pillar is also a database of information that can 
be referenced from state sls yaml files.  Pillar is data hosted 
on the master that is conditionally made available in the context 
of state execution on a particular minion.  Unlike grains, pillar data may change frequently.

Like state sls files, pillar files are yaml files with a `.sls` extension 
that by default utilize jinja as a templating engine.  Here is an example 
of an actual pillar file:
--- content end ---

Third cell:
--- content start (copy the raw markdown) ---
```
{%- set igroup = salt["grains.get"]("igroup") %}
{%- set sector = salt["grains.get"]("sector") %}

archiver:
  enriched:
    s3-bucket: {{ igroup }}.com.shpsec.{{ sector }}.sds-archiver.enriched
    kafka-enabled: true
    output:
      filehandler:
        remove_envelope_header: false

td-agent:
  sources:
    sds-enriched-aws-archiver:
      type: "tail"
      format: "none"
      path: "/opt/app/var/log/sds-enriched-aws-archiver/enriched-aws-archiver.log"
      pos_file: "/opt/app/td-agent/pos/sds-enriched-aws-archiver.pos"
      read_from_head: "true"
      tag: "sds-enriched-aws-archiver"
```
--- content end ---

Execute the markdown cells then shrink the width of the window.  The plain text in the first cell will stop wrapping once the window is less wide than the longest code line.  The second cell will continue to line wrap.

I checked and this is different than classic notebook, classic will continue to line wrap but it also line wraps the code which is worse behavior imho.

MacOS 10.12.6
Chrome 61.0.3163.100
