### ISSUE TITLE
Random styling issue

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyterlab/jupyterlab#5090]
I am seeing this weird styling artefact appear randomly in output areas since the last release of Jupyterlab. Rerunning the cell generally fixes the issue.

This occurs with any type of output, even textual.

![random](https://user-images.githubusercontent.com/2397974/43950938-0f7ab520-9c92-11e8-9fe9-93b6d55e3baf.gif)

**Comment by SylvainCorlay** [comment]
It appears that the css rule causing this is:

```css
.jp-CodeCell.jp-mod-outputsScrolled .jp-Cell-outputArea {
    overflow-y: auto;
    max-height: 200px;
    box-shadow: inset 0 0 6px 2px rgba(0, 0, 0, 0.3);
    margin-left: var(--jp-private-cell-scrolling-output-offset);
}
```

I don't understand why the `.jp-mod-outputsScrolled` class is applied to the code cell. This looks like a race condition.
