### ISSUE TITLE
Automatic Labeling of PRs

### ISSUE THREAD

**Issue by declanvk** [jupyterlab/jupyterlab#7729]
Based on [@jasongrout's comment](https://github.com/jupyterlab/jupyterlab/pull/7545#issuecomment-556546717), it would be useful to automatically label PRs based on the files that they change. Luckily, there is a Github Action that does exactly that: [actions/labeler](https://github.com/actions/labeler).

This action labels PRs based on a file that describes a mapping from label names to file globs. From their documentation, in the file `.github/labeler.yml`:

```yml
# Add 'label1' to any changes within 'example' folder or any subfolders
label1:
  - example/**/*

# Add 'label2' to any file changes within 'example2' folder
label2: example2/*
```

Some proposed auto-labels:
  - `tag:CSS` and `Design System CSS` are applied to all PRs that change CSS.
  - `tag:Design and UX` is applied to all changes to files in the `design/` directory.
  - `tag:Documentation` is applied to all changes to files in the `docs/` directory.
  - `tag:Examples` is applied to all changes to files in the `examples/` directory.
  - `tag:Testing` is applied to all changes to files in the `tests/` directory.
  - `pkg:*` labels are applied to all changes to files in their respective `package/*` directories, and other related directories such as `package/*-extension` or `package/*-interfaces`.

Also, when going through the labels I noticed a couple discrepancies:
 - `pkg:celltags`, `pkg:property-inspector`, `pkg:settingsregistry`, and `pkg:statedb` are missing from the set of labels.
 - `pkg:dataregistry`, `pkg:faq`, and `pkg:iframe` are not needed any longer because the packages do not exist.
