### ISSUE TITLE
Vim cursor not visible on search highlights

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#8207]
The positioning of vim cursor (below the tokens) does not work great when highlights (achieved by means of background) are applied to tokens. This could be worked around by bumping the cursor z-index and making it semi-transparent or outline only (but neither is perfect..). Observed when investigating https://github.com/krassowski/jupyterlab-lsp/issues/240 (where it is a bigger problem).

I *think* that this is an upstream (codemirror) issue, but I do not see how they could fix this without a major refactor - the cost-benefit tradeoff does not look great. Just looking for ideas to address this here.

## Reproduce

1. Enable vim mode: Settings → Text Editor Key Map → vim
2. Search for a string in the file editor
3. Move cursor over the highlighted region
4. See the cursor obscured by the highlight

![highlight_obscures_vim_cursor](https://user-images.githubusercontent.com/5832902/79013480-c1663800-7b60-11ea-9de9-5d18b7b27293.gif)

## Expected behavior

The cursor remains visible at the top of the highlight, but below the token text.

## Context

- JupyterLab version: 2.1

z-index for the vim cursor is set in: `.cm-fat-cursor div.CodeMirror-cursors`,
```css
.cm-fat-cursor div.CodeMirror-cursors {
    z-index: 1;
}
```

fill for the vim cursor is set in `.cm-fat-cursor .CodeMirror-cursor`

```css
.cm-fat-cursor .CodeMirror-cursor {
    width: auto;
    border: 0 !important;
    background: #7e7;
}
```
