### ISSUE TITLE
Add metadata and APIs for determining reusable mimerenderers and dependencies

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlab/jupyterlab#9993]
### Problem

Without gazing deep within typescript (or the live state of a running Lab) it is difficult to tell which mime types are supported by the currently-installed labextensions. With the smaller API than the full extension API, these are perhaps a thing that could pay back the highest dividends for re-use of federated modules outside of the full interactive context.

### Proposed Solution

- expand the definition of `mimeextension` in the metadata schema to offer canonical, low-barrier access to the mimetypes supported by an extension, e.g.

```yaml
"jupyter": {
  "lab": {
    "mimeExtension": {
      "path": "lib/mimerenderer.js",
      "mimetypes": ["vnd/whatever-viz-v1"]
    }
  }
}
```

- offer a pythonic API and CLI (either out of `jupyterlab_server` or this repo) to get the paths of required files to render a given set of mimetypes

```bash
$> jupyter lab mimextensions --json vnd/whatever-viz-v1 vnd/another-viz-v1 
{
  "paths": [
    "/srv/conda/share/labextensions/@whatever/viz/remoteEntry.<hash>.js",
    "/srv/conda/share/labextensions/@another/viz/remoteEntry.<hash>.js"
  ]
}
```

### Additional context

Discussed on [discourse](https://discourse.jupyter.org/t/feature-idea-a-specification-for-notebook-output-dependencies/8428/11) in the context of `jupyter-book`.

cc @choldgraf
